name: asset_pack
description: Asset Management Library for Dart Games
version: 0.6.0
authors:
- John McCutchan <john@johnmccutchan.com>
- Daniel Rodriguez <seth.illgard@gmail.com>
description: Asset Management Library for Dart Games
homepage: https://github.com/johnmccutchan/assetpack
dependencies:
  unittest: any
  browser: any
  bot: '>=0.15.0 <0.16.0'
  meta: any
  html5lib: any
  args: any
  logging: any
  pathos: any
  source_maps: any
